[env:proton]
platform = https://github.com/norandomtechie/platform-raspberrypi#feature/proton-picosdk-support
board = proton
framework = picosdk
build_src_flags = -O0
build_flags =
    -DPIO_NO_STDIO_UART=1
    -Iinclude
extra_scripts = pre:extra_script.py
debug_tool = picoprobe
upload_protocol = picoprobe
monitor_speed = 115200
