[env:proton]
platform = https://github.com/norandomtechie/platform-raspberrypi#feature/proton-picosdk-support
board = proton
framework = picosdk
build_src_flags = -O0
build_flags =
    -DPIO_NO_STDIO_UART=1
    -Iinclude
    -Ilib/pico-tflmicro/src
    -Ilib/pico-tflmicro/src/third_party/ruy
    -Ilib/pico-tflmicro/src/third_party/gemmlowp
    -Ilib/pico-tflmicro/src/third_party/kissfft
    -Ilib/pico-tflmicro/src/third_party/flatbuffers
    -Ilib/pico-tflmicro/src/third_party/flatbuffers/include
    -Ilib/pico-tflmicro/src/third_party/cmsis/CMSIS/Core/Include
    -Ilib/pico-tflmicro/src/third_party/cmsis_nn/Include
    -DTF_LITE_DISABLE_X86_NEON=1
    -DTF_LITE_STATIC_MEMORY=1
    -DTF_LITE_USE_CTIME=1
    -DCMSIS_NN=1
    -DTFLITE_USE_CTIME=1
    -std=gnu++17
    -fno-rtti
    -fno-exceptions
    -Wl,-z,muldefs
build_src_filter =
    +<*.c>
    +<*.cpp>
    +<*.pio.h>
lib_deps =
lib_ignore = pico-tflmicro
lib_archive = false
extra_scripts = pre:extra_script.py
debug_tool = picoprobe
upload_protocol = picoprobe
monitor_speed = 115200
