// ----------------------------------------------------------------- //
// This file is autogenerated by pioasm version v2.2.0; do not edit! //
// ----------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// -------------- //
// camera_capture //
// -------------- //

#define camera_capture_wrap_target 0
#define camera_capture_wrap 4
#define camera_capture_pio_version 0

static const uint16_t camera_capture_program_instructions[] = {
            //     .wrap_target
    0x2089, //  0: wait   1 gpio, 9
    0x2088, //  1: wait   1 gpio, 8
    0x4008, //  2: in     pins, 8
    0x2008, //  3: wait   0 gpio, 8
    0x00c1, //  4: jmp    pin, 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program camera_capture_program = {
    .instructions = camera_capture_program_instructions,
    .length = 5,
    .origin = -1,
    .pio_version = camera_capture_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x1
#endif
};

static inline pio_sm_config camera_capture_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + camera_capture_wrap_target, offset + camera_capture_wrap);
    return c;
}

#include "hardware/clocks.h"
#include "hardware/gpio.h"
static inline void camera_capture_program_init(PIO pio, uint sm, uint offset,
                                                uint data_base_pin, uint pclk_pin,
                                                uint href_pin) {
    pio_sm_config c = camera_capture_program_get_default_config(offset);
    // Set input pins: data bus starts at data_base_pin (8 consecutive pins)
    sm_config_set_in_pins(&c, data_base_pin);
    // JMP pin is HREF for the conditional jump
    sm_config_set_jmp_pin(&c, href_pin);
    // Shift ISR to the right, autopush every 32 bits
    sm_config_set_in_shift(&c, true, true, 32);
    // Configure all data pins as inputs
    for (uint i = 0; i < 8; i++) {
        pio_gpio_init(pio, data_base_pin + i);
    }
    pio_sm_set_consecutive_pindirs(pio, sm, data_base_pin, 8, false);
    // Configure PCLK and HREF as inputs
    pio_gpio_init(pio, pclk_pin);
    pio_gpio_init(pio, href_pin);
    pio_sm_set_consecutive_pindirs(pio, sm, pclk_pin, 1, false);
    pio_sm_set_consecutive_pindirs(pio, sm, href_pin, 1, false);
    // No clock divider - run at full system clock
    sm_config_set_clkdiv(&c, 1.0f);
    // Load config and start
    pio_sm_init(pio, sm, offset, &c);
}

#endif

